# netlify.toml
[build]
  command = "npm run build"
  publish = ".next"             

[functions]
  node_bundler = "esbuild"

SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SITE_URL"

[[plugins]]
  package = "@netlify/plugin-nextjs"
